package frontend

import (
	"embed"
	"io/fs"
	"os"
	"path/filepath"
)

// Assets is the production Vue application generated by `npm run build` in web/.
//
//go:embed all:assets
var Assets embed.FS

// Extract writes the embedded web application to dir on every start, allowing the
// existing static-file middleware to serve it while keeping the executable self-contained.
func Extract(dir string) error {
	return fs.WalkDir(Assets, "assets", func(path string, entry fs.DirEntry, err error) error {
		if err != nil || path == "assets" {
			return err
		}
		rel, err := filepath.Rel("assets", path)
		if err != nil {
			return err
		}
		destination := filepath.Join(dir, rel)
		if entry.IsDir() {
			return os.MkdirAll(destination, 0750)
		}
		content, err := Assets.ReadFile(path)
		if err != nil {
			return err
		}
		if err = os.MkdirAll(filepath.Dir(destination), 0750); err != nil {
			return err
		}
		return os.WriteFile(destination, content, 0644)
	})
}
